sonar.projectKey=Cybertourist_python-project-52
sonar.organization=cybertourist
sonar.sources=.
sonar.exclusions=**/migrations/**,**/tests.py,manage.py,**/settings.py,test_settings.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12